name: momentoboothcompanionapp
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Communication
  mqtt5_client: 4.2.2

  # Rust bridge
  flutter_rust_bridge: 2.0.0-dev.30
  rust_lib_momentoboothcompanionapp:
    path: rust_builder

  # UI tools
  widgetbook: 3.7.1
  widgetbook_annotation: 3.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  integration_test:
    sdk: flutter

  widgetbook_generator: 3.7.0

flutter:
  uses-material-design: true
  generate: true

scripts:
  run: rps install all && rps generate all
  install:
    all: rps install flutter && rps install cargo-expand && rps install flutter_rust_bridge_codegen && rps install deps
    flutter: fvm install
    cargo-expand: cargo install cargo-expand
    flutter_rust_bridge_codegen: cargo install flutter_rust_bridge_codegen --version 2.0.0-dev.30
    deps: fvm flutter pub get
  clean:
    rust_bridge: git clean -xfd lib/src
  generate:
    all: rps generate l10n && rps generate rust_bridge
    l10n: fvm flutter gen-l10n
    rust_bridge: rps clean rust_bridge && flutter_rust_bridge_codegen generate
    build_runner_targets: fvm dart run build_runner build --delete-conflicting-outputs
  update:
    rust-install: rustup update
  docs:
    install-deps: cargo install mdbook mdbook-mermaid mdbook-admonish
    build:
      $before: $docs install-deps
      $script: mdbook build documentation
