name: momentoboothcompanionapp
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI

  # Network
  mqtt5_client: 4.2.2

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
