name: momentoboothcompanionapp
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }

  # Communication
  mqtt5_client: 4.2.4

  # Models
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0
  fast_immutable_collections: 10.2.3

  # Rust bridge
  flutter_rust_bridge: 2.0.0-dev.34
  rust_lib_momentoboothcompanionapp: { path: rust_builder }

  # UI
  widgetbook: 3.7.1
  widgetbook_annotation: 3.1.0
  mobx: 2.3.3+2
  flutter_mobx: 2.2.1+1
  go_router: 14.1.2
  fluent_ui: 4.8.7
  lottie: 3.1.2
  window_manager: 0.3.9

  # l10n
  flutter_localizations: { sdk: flutter }
  intl: any

  # Misc
  get_it: 7.7.0
  synchronized: 3.1.0+1
  talker: 4.2.0
  meta: any

dev_dependencies:
  # Code quality
  flutter_lints: ^4.0.0
  integration_test: { sdk: flutter }

  # Models
  freezed: 2.5.2
  json_serializable: 6.8.0
  build_runner: ^2.4.10

  # UI
  widgetbook_generator: 3.7.0
  mobx_codegen: 2.6.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
