name: momentoboothcompanionapp
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }

  # Communication
  mqtt5_client: 4.2.4

  # Models
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0
  fast_immutable_collections: 10.2.3

  # Rust bridge
  flutter_rust_bridge: 2.0.0-dev.33
  rust_lib_momentoboothcompanionapp: { path: rust_builder }

  # UI
  widgetbook: 3.7.1
  widgetbook_annotation: 3.1.0
  mobx: 2.3.3+2
  flutter_mobx: 2.2.1+1
  go_router: 14.1.1
  fluent_ui: 4.8.7
  lottie: 3.1.1
  window_manager: 0.3.8

  # l10n
  flutter_localizations: { sdk: flutter }
  intl: any

  # Misc
  get_it: 7.7.0
  synchronized: 3.1.0+1
  talker: 4.2.0
  meta: any

dev_dependencies:
  # Code quality
  flutter_lints: ^4.0.0
  integration_test: { sdk: flutter }

  # Models
  freezed: 2.5.2
  json_serializable: 6.8.0
  build_runner: ^2.4.10

  # UI
  widgetbook_generator: 3.7.0
  mobx_codegen: 2.6.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/

scripts:
  run: rps install all && rps generate all
  install:
    all: rps install flutter && rps install cargo-expand && rps install flutter_rust_bridge_codegen && rps install deps
    flutter: fvm install
    cargo-expand: cargo install cargo-expand
    flutter_rust_bridge_codegen: cargo install flutter_rust_bridge_codegen --version 2.0.0-dev.33
    deps: fvm flutter pub get
  clean:
    rust_bridge: git clean -xfd lib/src
  generate:
    all: rps generate l10n && rps generate rust_bridge
    l10n: fvm flutter gen-l10n
    rust_bridge: rps clean rust_bridge && flutter_rust_bridge_codegen generate
    build_runner_targets: fvm dart run build_runner build --delete-conflicting-outputs
  update:
    rust-install: rustup update
  docs:
    install-deps: cargo install mdbook mdbook-mermaid mdbook-admonish
    build:
      $before: $docs install-deps
      $script: mdbook build documentation
