name: momentoboothcompanionapp
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI

  # Network
  mqtt5_client: 4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
