[package]
name = "rust_lib_momentoboothcompanionapp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.0.0-dev.38", features = ["chrono"] }
url = "2.5.0"
ipp = "5.0.3"
chrono = "0.4.38"

[profile.dev]
opt-level = 3
